### ISSUE TITLE
How to record particular view only ?

### ISSUE THREAD

**Issue by niravspaceo** [alskipp/ASScreenRecorder#11]
Hello, 
I have one uiview which is added in center. Now I want to record only that UIView.
I am trying to change below code in ASScreenRecorder.m .

  [window drawViewHierarchyInRect:CGRectMake(0, 0, _viewSize.width, _viewSize.height) afterScreenUpdates:NO];

But it is giving me strange results.

How to achieve this ?

**Comment by Japspre** [comment]
Have a look at this other issue. I added some pointers and code there

https://github.com/alskipp/ASScreenRecorder/issues/1
