### ISSUE TITLE
Appstore?

### ISSUE THREAD

**Issue by davut5** [alskipp/ASScreenRecorder#17]
App Store  reject this?    yes or no..?      can i use it?

can i use it with swift?

**Comment by alskipp** [comment]
No private APIs are used, so it shouldn't break any AppStore rules. I only use the project to record app videos, not as part of the actual app functionally, so I've never submitted it to the AppStore. It'll be fine to use in a Swift project. 

For iOS 10 apps it would be better to use https://developer.apple.com/reference/replaykit/rpscreenrecorder
