### ISSUE TITLE
[FPS] How change FPS of the video to 60/1?

### ISSUE THREAD

**Issue by MarcusXie** [alskipp/ASScreenRecorder#18]
If I change file to a video stream, and send it to other device, 
then how to change the FPS of screenRecorder?

thanks.

**Comment by MarcusXie** [comment]
reference here: https://github.com/alskipp/ASScreenRecorder/issues/8

**Comment by MarcusXie** [comment]
No.8 can't solve my problem. I could not change the FPS to 60.
any help?

**Comment by alskipp** [comment]
Only in the very best case scenario can you expect 60 fps and it depends on which device you're using and the complexity of the view.

**Comment by MarcusXie** [comment]
Thanks!
