### ISSUE TITLE
In background Mode

### ISSUE THREAD

**Issue by nbansal2211** [alskipp/ASScreenRecorder#19]
I try to run this application in background mode. it give me black screen in video. could you pleasse help me how can  use this code in background mode also.

**Comment by alskipp** [comment]
Once your app is in the background it doesn't render anything to the screen so there is nothing to record. 

If you would like to record the screen outside the domain of your app, this is simply impossible to do on iOS (without jail breaking the device). 

So unfortunately there is no way to record the screen while your app is in the background using public APIs.
